  - name: build
    run: |
      sudo apt-get update
      sudo apt-get install -y ninja-build
      wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
      unzip android-ndk-r21e-linux-x86_64.zip
      export ANDROID_NDK_HOME=$PWD/android-ndk-r21e
      export PATH=$ANDROID_NDK_HOME:$PATH

  - name: Build native for all ABIs
    run: |
      ABIs=("arm64-v8a" "armeabi-v7a" "x86" "x86_64")
      for ABI in "${ABIs[@]}"; do
          mkdir -p build/$ABI
          cmake -S . -B build/$ABI -G Ninja \
              -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=$ABI \
              -DANDROID_NATIVE_API_LEVEL=21 \
              -DCMAKE_BUILD_TYPE=Release
          cmake --build build/$ABI
      done
      
